name: Model Accuracy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  accuracy-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pandas duckdb scikit-learn bambi pymc arviz

    - name: Generate synthetic data for CI
      run: |
        # In a real-world scenario, this would pull a versioned, static test dataset
        # from cloud storage. For this demo, we generate it on the fly.
        echo "Generating synthetic data for CI..."
        python -c "from flight_delay_bayes.ingestion.bts_bulk_ingest import ingest_bulk; ingest_bulk(2022, 2023)"
        
    - name: Run walk-forward validation (quick)
      id: walk_cv
      run: |
        python -m flight_delay_bayes.cli walk-cv --quick --start-year 2023 --json-output .ci/results.json

    - name: Check for performance regression
      run: |
        python .ci/check_regression.py .ci/results.json .ci/target.json 